FROM oracle/graalvm-ce:19.1.0 as graalvm
RUN gu install native-image
COPY . /home/app/user-service-ords
WORKDIR /home/app/user-service-ords
RUN native-image --no-server --no-fallback --initialize-at-build-time=com.sun.el.ExpressionFactoryImpl -cp build/libs/user-service-ords-*.jar

FROM frolvlad/alpine-glibc
EXPOSE 8080
COPY --from=graalvm /home/app/user-service-ords .
ENTRYPOINT ["./user-service-ords"]