= Cloud Native Microservices - User Service

= Table of Contents

* link:#cloud-native-microservices---user-service[Cloud Native Microservices - User Service]
* link:#framework[Framework]
* link:#setup[Setup]
** link:#ords-auto-rest-enable[ORDS 'Auto' REST Enable]
** link:#custom-ords-services[Custom ORDS Services]
* link:#dependencies[Dependencies]
* link:#building[Building]
* link:#setting-environment-variables[Setting environment variables]
* link:#running[Running]
* link:#test-endpoints[Test Endpoints]
* link:#view-health-and-metrics[View Health and Metrics]
* link:#dockerfile[Dockerfile]
* link:#building-the-docker-image[Building the Docker Image]
* link:#running-with-docker[Running with Docker]
* link:#building-a-docker-image-that-runs-a-graal-native-image[Building a Docker Image That Runs A Graal Native Image]
* link:#running-the-graal-based-docker-image[Running the Graal Based Docker Image]
* link:#building-for-deployment[Building for Deployment]
* link:#deploying-to-kubernetes[Deploying to Kubernetes]
** link:#create-secret[Create Secret]

== Framework

This service utilizes Micronaut with ORDS to persist users to a `user` table in an Oracle ATP instance.

To learn more about ORDS, refer to https://blogs.oracle.com/developers/rest-services-now-available-for-oracle-autonomous-database[this blog post].

== Setup

'''

____

*Note*: It is not required to run the Micronaut CLI setup scripts below if you've cloned this repository. They are included for reference only.

____

'''

This service was created using the Micronaut CLI like so:

[source,bash]
----
mn create-app codes.recursive.cnms.ords.user-service-ords
----

If you'd like support for GraalVM, create the app with the following command instead:

[source,bash]
----
mn create-app codes.recursive.cnms.ords.user-service-ords --features graal-native-image
----

'''

____

*Note*: You will, however, need to run these SQL scripts…

____

'''

The DDL to create the database table looks like so:

Create the schema/user:

[source,sql]
----
CREATE USER usersvc IDENTIFIED BY "STRONGPASSWORD";
GRANT create session TO usersvc;
GRANT create table TO usersvc;
GRANT create view TO usersvc;
GRANT create any trigger TO usersvc;
GRANT create any procedure TO usersvc;
GRANT create sequence TO usersvc;
GRANT create synonym TO usersvc;
GRANT CONNECT TO usersvc;
GRANT RESOURCE TO usersvc;
GRANT UNLIMITED TABLESPACE TO usersvc;
----

Create the necessary table(s):

[source,sql]
----
CREATE TABLE users(
    "ID" VARCHAR2(32 BYTE) DEFAULT ON NULL SYS_GUID(), 
	"FIRST_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CREATED_ON" TIMESTAMP (6) DEFAULT ON NULL CURRENT_TIMESTAMP, 
	 CONSTRAINT "USER_PK" PRIMARY KEY ("ID")
);
----

=== ORDS 'Auto' REST Enable

Out of the box, Auto REST enabling a table will give you endpoints to perform the following actions:

* GET (by ID)
* GET (all - with pagination support)
* POST (new record)
* PUT (update record)
* DELETE (by ID)

To REST enable the schema and the table:

[source,sql]
----
BEGIN
    /* enable ORDS for schema */
    ORDS.ENABLE_SCHEMA(p_enabled => TRUE,
                       p_schema => 'USERSVC',
                       p_url_mapping_type => 'BASE_PATH',
                       p_url_mapping_pattern => 'usersvc',
                       p_auto_rest_auth => FALSE);
     /* enable ORDS for table */         
    ORDS.ENABLE_OBJECT(p_enabled => TRUE,
                       p_schema => 'USERSVC',
                       p_object => 'USERS',
                       p_object_type => 'TABLE',
                       p_object_alias => 'users',
                       p_auto_rest_auth => FALSE);
    COMMIT;
END;
----

*Note*: The argument `p_auto_rest_auth` being set to `FALSE` means that all unauthenticated requests will return a `401 Unauthorized` meaning we'll have to send credentials with each REST call.

Create a new privilege:

[source,sql]
----
DECLARE
 l_roles     OWA.VC_ARR;
 l_modules   OWA.VC_ARR;
 l_patterns  OWA.VC_ARR;
BEGIN
 l_roles(1)   := 'SQL Developer';
 l_patterns(1) := '/users/*';
 ORDS.DEFINE_PRIVILEGE(
     p_privilege_name => 'rest_privilege',
     p_roles          => l_roles,
     p_patterns       => l_patterns,
     p_modules        => l_modules,
     p_label          => '',
     p_description    => '',
     p_comments       => NULL);
 COMMIT;

END;
----

Create an oauth client associated with the privilege:

[source,sql]
----
BEGIN
  OAUTH.create_client(
    p_name            => '[Descriptive Name For Client]',
    p_grant_type      => 'client_credentials',
    p_owner           => '[Owner Name]',
    p_description     => '[Client Description]',
    p_support_email   => '[Email Address]',
    p_privilege_names => 'rest_privilege'
  );

  COMMIT;
END;
----

Grant the `SQL Developer` role to the client application:

[source,sql]
----
BEGIN
  OAUTH.grant_client_role(
    p_client_name => 'Rest Client',
    p_role_name   => 'SQL Developer'
  );
  
  COMMIT;
END;
----

You can now grab the `client_id` and `client_secret` with:

[source,sql]
----
SELECT id, name, client_id, client_secret
FROM   user_ords_clients;
----

The `client_id` and `client_secret` can be used to generate an auth token for REST calls (this microservice handles this for you). To run the microservice, you'll need the `client_id` and `client_secret` set as environment variables to run the application. See link:#setting-environment-variables[setting environment variables].

=== Custom ORDS Services

You can create custom ORDS services like so (returns a single record instead of a set of results):

[source,sql]
----
BEGIN
  ORDS.define_service(
    p_module_name    => 'users',
    p_base_path      => 'users/',
    p_pattern        => 'user/:username',
    p_method         => 'GET',
    p_source_type    => ORDS.source_type_collection_item,
    p_source         => 'SELECT id, first_name, last_name, created_on FROM users WHERE username = :username OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY');
  COMMIT;
END;
----

== Dependencies

This project has no manually installed external dependencies.

== Building

[source,bash]
----
gradle assemble
----

Or, use the Gradle wrapper:

[source,bash]
----
./gradlew assemble
----

== Setting environment variables

Set environment variables as follows:

[source,bash]
----
export CODES_RECURSIVE_CNMS_ORDS_CLIENT_ID=[CLIENT ID]
export CODES_RECURSIVE_CNMS_ORDS_CLIENT_SECRET=[CLIENT SECRET]
export CODES_RECURSIVE_CNMS_ORDS_BASE_URL=[ATP ORDS BASE URL]
----

== Running

[source,bash]
----
java -jar build/libs/user-service-ords-0.1.jar
----

== Test Endpoints

Get User Service Endpoint (returns 200 OK):

[source,bash]
----
curl -iX GET http://localhost:8080/user                                                                                                                                      
HTTP/1.1 200 OK
Date: Tue, 2 Jul 2019 14:04:25 GMT
content-type: application/json
content-length: 11
connection: keep-alive

{"OK":true}     
----

Save (POST) a new user:

[source,bash]
----
curl -iX POST -H "Content-Type: application/json" -d '{"first_name": "Tony", "last_name": "Stark", "username": "ironman"}' http://localhost:8080/user
HTTP/1.1 201 Created
Date: Tue, 9 Jul 2019 05:55:17 GMT
content-type: application/json
content-length: 142
connection: keep-alive

{"id":"8D397B08E839FD7EE0531F10000AF8D1","username":"ironman","first_name":"Tony","last_name":"Stark","created_on":"2019-07-09T05:55:16.086Z"}
----

Save a new user with invalid data (will return 400 and validation errors):

[source,bash]
----
curl -iX POST -H "Content-Type: application/json" -d '{"first_name": null, "last_name": null, "username": null}' http://localhost:8080/user
HTTP/1.1 400 Bad Request
Date: Tue, 9 Jul 2019 05:56:13 GMT
content-type: application/json
content-length: 296
connection: close

{"message":"Bad Request","_links":{"self":{"href":"/user","templated":false}},"_embedded":{"errors":[{"message":"user.username: must not be null"},{"message":"user.firstName: must not be null"},{"message":"user.lastName: must not be null"},{"message":"user: Username must exist and be unique"}]}}
----

Update (PUT) an existing user:

[source,bash]
----
curl -iX PUT -H "Content-Type: application/json" -d '{"id":"8D397B08E839FD7EE0531F10000AF8D1","username":"ironman","first_name":"Anthony","last_name":"Stark","created_on":"2019-07-09T05:55:16.086Z"}' http://localhost:8080/user
HTTP/1.1 200 OK
Date: Tue, 9 Jul 2019 05:57:52 GMT
content-type: application/json
content-length: 145
connection: keep-alive

{"id":"8D397B08E839FD7EE0531F10000AF8D1","username":"ironman","first_name":"Anthony","last_name":"Stark","created_on":"2019-07-09T05:55:16.086Z"}
----

Get the new user

[source,bash]
----
curl -iX GET http://localhost:8080/user/8D397B08E839FD7EE0531F10000AF8D1
HTTP/1.1 200 OK
Date: Tue, 9 Jul 2019 05:59:00 GMT
content-type: application/json
content-length: 145
connection: keep-alive

{"id":"8D397B08E839FD7EE0531F10000AF8D1","username":"ironman","first_name":"Anthony","last_name":"Stark","created_on":"2019-07-09T05:55:16.086Z"}%----

List all users:

[source,bash]
----
curl -iX GET http://localhost:8080/user/users
HTTP/1.1 200 OK
Date: Tue, 9 Jul 2019 05:59:44 GMT
content-type: application/json
content-length: 777
connection: keep-alive

{"offset":0,"count":5,"hasMore":false,"limit":25,"users":[{"id":"8C561D58E856DD25E0532010000AF462","username":"tsharp","first_name":"todd","last_name":"sharp","created_on":"2019-06-27T15:31:40.385Z"},{"id":"8C561D58E857DD25E0532010000AF462","username":"gvenzl","first_name":"gerald","last_name":"venzl","created_on":"2019-06-27T15:31:40.517Z"},{"id":"8C561D58E858DD25E0532010000AF462","username":"thatjeff","first_name":"jeff","last_name":"smith","created_on":"2019-06-27T15:31:40.646Z"},{"id":"8D397B08E836FD7EE0531F10000AF8D1","username":"test","first_name":"Tony","last_name":"Stark","created_on":"2019-07-09T05:03:21.511Z"},{"id":"8D397B08E839FD7EE0531F10000AF8D1","username":"ironman","first_name":"Anthony","last_name":"Stark","created_on":"2019-07-09T05:55:16.086Z"}]}
----

List all users (paginated):

[source,bash]
----
curl -iX GET http://localhost:8080/user/users/0/1
HTTP/1.1 200 OK
Date: Tue, 9 Jul 2019 06:00:14 GMT
content-type: application/json
content-length: 201
connection: keep-alive

{"offset":0,"count":1,"hasMore":true,"limit":1,"users":[{"id":"8C561D58E856DD25E0532010000AF462","username":"tsharp","first_name":"todd","last_name":"sharp","created_on":"2019-06-27T15:31:40.385Z"}]}
----

Delete a user:

[source,bash]
----
curl -iX DELETE http://localhost:8080/user/8CB41C8DFB2FA3F6E0532010000A42F8
HTTP/1.1 204 No Content
Date: Tue, 2 Jul 2019 14:06:50 GMT
connection: keep-alive
----

Confirm delete (same GET by ID will return 404):

[source,bash]
----
curl -iX GET http://localhost:8080/user/8CB41C8DFB2FA3F6E0532010000A42F8
HTTP/1.1 404 Not Found
Date: Tue, 9 Jul 2019 06:02:48 GMT
content-type: application/json
content-length: 114
connection: close

{"message":"Page Not Found","_links":{"self":{"href":"/user/8D39D3D515CE1123E0531F10000A8A5B","templated":false}}}
----

Get user by username:

[source,bash]
----
curl -iX GET http://localhost:8080/user/username/ironman
HTTP/1.1 200 OK
Date: Wed, 3 Jul 2019 19:23:55 GMT
content-type: application/json
content-length: 121
connection: keep-alive

{"id":"8CB931BBDA2ABCF7E0532010000A09C7","first_name":"Tony","last_name":"Stark","created_on":"2019-07-02T20:00:02.049Z"}
----

== View Health and Metrics

Micronaut does not enable health and metrics out of the box, but they are available via an add-on project. 

For more, see https://docs.micronaut.io/latest/guide/index.html#management[https://docs.micronaut.io/latest/guide/index.html#management]

== Dockerfile

The generated `Dockerfile` requires some changes. See the `Dockerfile` for reference.

== Building the Docker Image

[source]
----
docker build -t user-svc-micronaut-native .
----

== Running with Docker

Run with: 

[source,bash]
----
docker run -d --env CODES_RECURSIVE_CNMS_ORDS_CLIENT_ID --env CODES_RECURSIVE_CNMS_ORDS_CLIENT_SECRET --env CODES_RECURSIVE_CNMS_ORDS_BASE_URL --rm -p 8080:8080 -t user-svc-micronaut
----

Test the endpoints as link:#test-endpoints[described above]

== Building a Docker Image That Runs A Graal Native Image

[source,bash]
----
docker build -f Dockerfile-graal -t user-svc-micronaut-native . 
----

== Running the Graal Based Docker Image

[source,bash]
----
docker run -d --env CODES_RECURSIVE_CNMS_ORDS_CLIENT_ID --env CODES_RECURSIVE_CNMS_ORDS_CLIENT_SECRET --env CODES_RECURSIVE_CNMS_ORDS_BASE_URL --rm -p 8080:8080 -t user-service-ords-native
----

== Building for Deployment

[source,bash]
----
docker build -f Dockerfile-graal -t [region].ocir.io/[tenancy]/[repo]/user-svc-micronaut-native .   
docker push [region].ocir.io/[tenancy]/[repo]/user-svc-micronaut-native
----

Test the endpoints as link:#test-endpoints[described above]

== Deploying to Kubernetes

=== Create Secret

Base64 encode the secret values before creating the YAML file.

On *nix systems, use something like this to accomplish for each value:

[source,bash]
----
echo -n "client_id.." | base64
----

Then create a YAML file:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: user-svc-micronaut-native-secrets
data:
  clientId: [ORDS Client ID Base64 Encoded]
  clientSecret: [ORDS Client Secret Base64 Encoded]
  baseUrl: [ORDS Base URL Base64 Encoded]
---
----

Deploy secret and app via:

[source]
----
kubectl cluster-info                         # Verify which cluster
kubectl get pods                             # Verify connectivity to cluster
kubectl create -f secret.yaml               # Deploy secret
kubectl create -f app.yaml               # Deploy application
kubectl get service user-svc-micronaut-native  # Verify deployed service
----